# Copyright (c) Shanghai AI Lab. All rights reserved.
# from .beit_adapter import BEiTAdapter
# from .beit_baseline import BEiTBaseline
# from .vit_adapter import ViTAdapter
# from .vit_baseline import ViTBaseline
# from .uniperceiver_adapter import UniPerceiverAdapter
# from .beit_adapter_multimodal import BEiTAdaptermultimodal
from .image_encoder import ImageEncoderViT
from .image_encoder_adapter_multimodal import SAMAdaptermultimodal
from .image_encoder_adapter_multimodal_no_gamma_extractor_and_final import SAMAdaptermultimodalnogamma
from .image_encoder_adapter_multimodal_gamma_spatial_image_based_no_gamma_extractor import SAMAdaptermultimodalselectorgamma
from .image_encoder_adapter_multimodal_gamma_spatial_image_based_no_gamma_extractor_no_gammac1 import SAMAdaptermultimodalselectorgamma_nogammac1
from .image_encoder_adapter_multimodal_gamma_spatial_image_based_no_gamma_final import SAMAdaptermultimodalselectorgamma_nogammafinal
from .image_encoder_adapter_multimodal_gamma_spatial_image_based_no_gamma_final_one_adapter_branch import SAMAdaptermultimodalselectorgamma_nogammafinalonebranch
from .image_encoder_adapter_multimodal_gamma_spatial_image_based_no_gamma_final_one_adapter_branch_layer_norm import SAMAdaptermultimodalselectorgamma_nogammafinalonebranchLayerNorm
from .image_encoder_adapter_multimodal_gamma_spatial_image_based_no_gamma_final_one_adapter_branch_relu_norm import SAMAdaptermultimodalselectorgamma_nogammafinalonebranchReluNorm
from .image_encoder_adapter_multimodal_gamma_spatial_image_based_no_gamma_final_one_adapter_branch_softmax import SAMAdaptermultimodalselectorgamma_nogammafinalonebranchSoftmax
from .image_encoder_adapter_multimodal_gamma_spatial_image_based_no_gamma_final_one_adapter_branch_relu_Layernorm import SAMAdaptermultimodalselectorgamma_nogammafinalonebranchReluLayernorm
from .image_encoder_adapter_multimodal_gamma_spatial_image_based_no_gamma_final_one_adapter_branch_relu_Layernorm_mod_spm_gamma import SAMAdaptermultimodalselectorgamma_nogammafinalonebranchReluLayernormspmmod
from .image_encoder_adapter_multimodal_gamma_spatial_image_based_no_gamma_final_one_adapter_branch_relu_Batchnorm_mod_spm_gamma import SAMAdaptermultimodalselectorgamma_nogammafinalonebranchReluBatchnormspmmod
from .image_encoder_adapter_multimodal_gamma_spatial_image_based_no_gamma_final_one_adapter_branch_relu_norm_mod_spm_gamma import SAMAdaptermultimodalselectorgamma_nogammafinalonebranchRelunormsum
from .image_encoder_adapter_multimodal_gamma_spatial_image_based_no_gamma_final_one_adapter_branch_relu_norm_mod_spm_gamma_concat import SAMAdaptermultimodalselectorgamma_nogammafinalonebranchRelunormsum_concat
from .image_encoder_adapter_multimodal_gamma_spatial_image_based_no_gamma_final_one_adapter_branch_relu_norm_mod_spm_gamma_with_learnable import SAMAdaptermultimodalselectorgamma_nogammafinalonebranchRelunormsumgammalearnable
from .image_encoder_adapter_multimodal_gamma_spatial_image_based_no_gamma_final_two_adapter_branch_relu_norm_mod_spm_gamma import SAMAdaptermultimodalselectorgamma_nogammafinaltwobranchRelunormsum
from .image_encoder_adapter_multimodal_gamma_spatial_image_based_no_gamma_final_one_adapter_branch_relu_Batchnorm_mod_spm_gamma_no_sum import SAMAdaptermultimodalselectorgamma_nogammafinalonebranchReluBatchnormspmmod_nosum
from .image_encoder_adapter_multimodal_gamma_spatial_image_based_no_gamma_final_two_adapter_branch_relu_norm_mod_spm_gamma_concat_inj import SAMAdaptermultimodalselectorgamma_nogammafinaltwobranchRelunormsum_concatinj
from .image_encoder_adapter_onlyDEPTH import SAMAdapterRGBDEPTH
from .image_encoder_adapter_onlyDEPTH_levelembed import SAMAdapterRGBDEPTH_levelembed
from .image_encoder_adapter_multimodal_1mod_selector_image_based_one_adapter_branch_relu_norm import SAMAdaptermultimodal1modselectoronebranchRelunorm
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm import SAMAdaptermultimodal4modselectoronebranchRelunorm
from .image_encoder_adapter_multimodal_nomod_selector_image_based_one_adapter_branch import SAMAdaptermultimodalnomodselectoronebranch
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_FPN import SAMAdaptermultimodal4modselectoronebranchRelunormFPN
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_level_embed import SAMAdaptermultimodal4modselectoronebranchRelunormlevemb
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concat import SAMAdaptermultimodal4modselectoronebranchRelunormconcat
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_BN import SAMAdaptermultimodal4modselectoronebranchRelunormBN
from .image_encoder_adapter_only1mod import SAMAdapterRGB1mod
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_modality_selector_separated import SAMAdaptermultimodal4modselectoronebranchRelunormseparated
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_FPN_reversed import SAMAdaptermultimodal4modselectoronebranchRelunormFPNreversed
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concat_less import SAMAdaptermultimodal4modselectoronebranchRelunormconcatless
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concat_l2 import SAMAdaptermultimodal4modselectoronebranchRelunormconcatl2
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concatBN import SAMAdaptermultimodal4modselectoronebranchRelunormconcatBN
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concat_transpose_conv import SAMAdaptermultimodal4modselectoronebranchRelunormconcatTrans
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_relu_norm import SAMAdapterbimodal4modselectoronebranchRelunorm
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concat import SAMAdapterbimodal4modselectoronebranchRelunormconcat
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concat_less import SAMAdapterbimodal4modselectoronebranchRelunormconcatless
from .image_encoder_adapter_bimodal_4mod_one_adapter_branch import SAMAdapterbimodal4modselectoronebranch
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concat_less_c1 import SAMAdapterbimodal4modselectoronebranchRelunormconcatlessc1
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concatv2 import SAMAdapterbimodal4modselectoronebranchRelunormconcatv2
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concat_lessv2 import SAMAdaptermultimodal4modselectoronebranchRelunormconcatlessv2
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concat_less_c1_eden import SAMAdapterbimodal4modselectoronebranchRelunormconcatlessc1eden
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature import SAMAdapterbimodal4modselectoronebranchModFromSp
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature_modality_selector_from_vit import SAMAdapterbimodal4modselectoronebranchModFromSpModfromViT
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_vit import SAMAdapterbimodal4modselectoronebranchModFromViT
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature_modality_selector_from_vit_v2 import SAMAdapterbimodal4modselectoronebranchModFromSpModfromViTv2
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature_SOFTMAX import SAMAdapterbimodal4modselectoronebranchModFromSpSOFTMAX
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature import SAMAdaptermultimodal4modselectoronebranchModFromSp
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_vit import SAMAdaptermultimodal4modselectoronebranchModFromViT
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_single_channel_by_mod import SAMAdaptermultimodal4modselectoronebranchModsinglechannelByMod
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature_smoother import SAMAdapterbimodal4modselectoronebranchModFromSpsmooth
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature_SOFTMAX_init import SAMAdapterbimodal4modselectoronebranchModFromSpSOFTMAX_init
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature_modality_selector_from_vit_v3 import SAMAdapterbimodal4modselectoronebranchModFromSpModfromViTv3
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature_modality_selector_from_vit_v4 import SAMAdapterbimodal4modselectoronebranchModFromSpModfromViTv4
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature_SOFTMAX import SAMAdaptermultimodal4modselectoronebranchModFromSpSOFTMAX
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature_SOFTMAX_DROPATH import SAMAdaptermultimodal4modselectoronebranchModFromSpSOFTMAXDROPATH
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature_SOFTMAX_DROPATH import SAMAdapterbimodal4modselectoronebranchModFromSpSOFTMAXDROPATH
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_single_channel_by_mod_lighter import SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModlighter
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_single_channel_by_mod_lighter_sam_mod import SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModlighterSAMmod
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_single_channel_by_mod_lighter_sam_modGELU import SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModlighterSAMmodGELU
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_featureGELU import SAMAdaptermultimodal4modselectoronebranchModFromSpGELU
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature_bigger import SAMAdaptermultimodal4modselectoronebranchModFromSpbigger
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature_lighter import SAMAdaptermultimodal4modselectoronebranchModFromSplighter
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature_DROPATH import SAMAdaptermultimodal4modselectoronebranchModFromSpDROPATH
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature_DROPATH_BOTH import SAMAdaptermultimodal4modselectoronebranchModFromSpDROPATHBOTH
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature_DROPOUT import SAMAdaptermultimodal4modselectoronebranchModFromSpDROPOUT
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature_bigger_SOFTMAX import SAMAdaptermultimodal4modselectoronebranchModFromSpbiggerSOFTMAX
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_single_channel_by_mod_DROPATH_no_RGB_BRANCH import SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModDropathnoRGBbranch
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_single_channel_by_mod_DROPATH_no_RGB_BRANCH_no_mod_RGB import SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModDropathnoRGBbranchnoModRGB
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_single_channel_by_mod_DROPATH_no_RGB_BRANCH_variant import SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModDropathnoRGBbranchvar
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_single_channel_by_mod_DROPATH_no_RGB_BRANCH_lighter import SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModDropathnoRGBbranchlighter
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_single_channel_by_mod_DROPATH_no_RGB_BRANCH_variant_concat import SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModDropathnoRGBbranchvarconcat
# from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_single_channel_by_mod_DROPATH_no_RGB_BRANCH_variant_concat_lighter_smart import SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModDropathnoRGBbranchvarconcatlightersmart
# from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_single_channel_by_mod_DROPATH_no_RGB_BRANCH_variant_concat_smart import SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModDropathnoRGBbranchvarconcatsmart
from .image_encoder_no_adapter import SAMnoAdapter
from .image_encoder_adapter_bimodal_2_adapter_branch import SAMAdapterbimodal2branch
# from .image_encoder_adapter_bimodal_2_adapter_branch_MINKOVSKY import SAMAdapterbimodal2branchMINK
# from .image_encoder_adapter_only1mod_MINKOVSKY import SAMAdapterRGB1modMinkovsky
from .image_encoder_adapter_bimodal_2_adapter_branch_concat import SAMAdapterbimodal2branchconcat
from .image_encoder_adapter_bimodal_concat import SAMAdapterbimodalconcat
from .image_encoder_adapter_bimodal_concat_lora import SAMAdapterbimodalconcatLORA
from .image_encoder_no_adapter_lora import SAMnoAdapterLORA
from .image_encoder_adapter_bimodal_2_adapter_branch_concat_LORA import SAMAdapterbimodal2branchconcatLORA
# from .image_encoder_adapter_bimodal_2_adapter_branch_concat_MINKOVSKY import SAMAdapterbimodal2branchconcatMINK
# from .image_encoder_adapter_bimodal_concat_MINKOVSKY import SAMAdapterbimodalconcatMINK
from .image_encoder_adapter_bimodal_concat_GELU import SAMAdapterbimodalconcatGELU
from .image_encoder_adapter_bimodal_2_adapter_branch_concat_GELU import SAMAdapterbimodal2branchconcatGELU
from .image_encoder_adapter_bimodal_concat_smart import SAMAdapterbimodalconcatSMART
from .image_encoder_adapter_bimodal_concat_SCORE import SAMAdapterbimodalconcatSCORE
from .image_encoder_adapter_bimodal_concat_SCORE_SMART import SAMAdapterbimodalconcatSCORESMART
from .image_encoder_adapter_bimodal_concat_SCORE_common import SAMAdapterbimodalconcatSCOREcommon
from .image_encoder_adapter_bimodal_SCORE_common import SAMAdapterbimodalSCOREcommon
from .image_encoder_adapter_bimodal_SCORE_common_lora import SAMAdapterbimodalSCOREcommonLORA
from .image_encoder_adapter_bimodal_early_fusion import SAMAdapterbimodal4modselectoronebranchEARLYFUSION
from .image_encoder_adapter_bimodal_2_adapter_branch_sequential import SAMAdapterbimodal2branchseq #SAMAdapterbimodal2branchfusion
from .image_encoder_adapter_bimodal_2_adapter_branch_sequential_fusion import SAMAdapterbimodal2branchseqfusion
from .image_encoder_adapter_bimodal_2_adapter_branch_sequential_no_final_add import SAMAdapterbimodal2branchseqnofinadd
from .image_encoder_adapter_bimodal_2_adapter_branch_sequential_ADA import SAMAdapterbimodal2branchseqADA
from .image_encoder_adapter_only1mod_DEBUG import SAMAdapterRGB1moddebug
from .image_encoder_adapter_bimodal_concat_noRELU import SAMAdapterbimodalconcatnoRELU
from .image_encoder_adapter_bimodal_concat_noRELU_patch_embed_mod import SAMAdapterbimodalconcatnoRELUpatchembedmod
from .image_encoder_adapter_bimodal_concat_noRELU_sum_onlyRGB import SAMAdapterbimodalconcatnoRELUsumonlyRGB
from .image_encoder_adapter_bimodal_mix_mod import SAMAdapterbimodalMixMod
from .image_encoder_adapter_bimodal_mix_mod_new_in import SAMAdapterbimodalMixModNewIn
from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_convnext import SAMAdapterbimodalMixModNewInTwinConv
from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_convnext_new import SAMAdapterbimodalMixModNewInTwinConvNEW
from .image_encoder_adapter_bimodal_mix_mod_new_in_shared_convnext_new import SAMAdapterbimodalMixModNewInSharedConvNEW
from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_convnext_new_with_cp import SAMAdapterbimodalMixModNewInTwinConvNEWwithcp
from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_convnext_new_with_cp_lora import SAMAdapterbimodalMixModNewInTwinConvNEWwithcpLORA
from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_convnext_new_with_cp_thinner import SAMAdapterbimodalMixModNewInTwinConvNEWwithcpthinner

from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_convnext_new_thinner import SAMAdapterbimodalMixModNewInTwinConvNEWthinner

from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_convnext_new_with_cp_THIN import SAMAdapterbimodalMixModNewInTwinConvNEWwithcpTHIN

from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_convnext_new_THIN import SAMAdapterbimodalMixModNewInTwinConvNEWTHIN
from .image_encoder_adapter_multimodal_single_convnext import SAMAdaptermultimodalsingleConvNext
from .image_encoder_adapter_bimodal_sum_mod_new_in_twin_convnext_new import SAMAdapterbimodalSumModNewInTwinConvNEW
from .image_encoder_adapter_monomodal_new_in_convnext_new import SAMAdaptermonomodalNewInConvNEW

from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_convnext_new_SWIN import SAMAdapterbimodalMixModNewInTwinConvNEWSWIN
from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_convnext_new_with_cp_SWIN import SAMAdapterbimodalMixModNewInTwinConvNEWwithcpSWIN
from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_convnext_new_lora import SAMAdapterbimodalMixModNewInTwinConvNEWLORA
from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_convnext_new_with_cp_no_SAM_weight import SAMAdapterbimodalMixModNewInTwinConvNEWwithcpnoweight
from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_spm_new import SAMAdapterbimodalMixModNewInTwinSPMNEW
from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_spm_new_ms import SAMAdapterbimodalMixModNewInTwinSPMNEWMS
from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_convnext_new_concat import SAMAdapterbimodalMixModNewInTwinConvNEWconcat
from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_convnext_new_fusion import SAMAdapterbimodalMixModNewInTwinConvNEWFUSION
from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_convnext_new_ms import SAMAdapterbimodalMixModNewInTwinCONVNEWMS
from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_convnext_new_fusion_better import SAMAdapterbimodalMixModNewInTwinConvNEWFUSIONBETTER
from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_convnext_new_fusion_simpler import SAMAdapterbimodalMixModNewInTwinConvNEWFUSIONSIMPLER
from .image_encoder_adapter_bimodal_mix_mod_new_in_twin_convnext_new_fusion_medium import SAMAdapterbimodalMixModNewInTwinConvNEWFUSIONMEDIUM

__all__ = ['ViTBaseline', 'ViTAdapter',
           'BEiTAdapter', 'ImageEncoderViT',
           'BEiTAdaptermultimodal','SAMAdaptermultimodal','SAMAdaptermultimodalnogamma','SAMAdaptermultimodalselectorgamma', 'SAMAdaptermultimodalselectorgamma_nogammac1', 'SAMAdaptermultimodalselectorgamma_nogammafinal','SAMAdaptermultimodalselectorgamma_nogammafinalonebranch', 'SAMAdaptermultimodalselectorgamma_nogammafinalonebranchLayerNorm','SAMAdaptermultimodalselectorgamma_nogammafinalonebranchReluNorm', 'SAMAdaptermultimodalselectorgamma_nogammafinalonebranchSoftmax','SAMAdaptermultimodalselectorgamma_nogammafinalonebranchReluLayernorm', 'SAMAdaptermultimodalselectorgamma_nogammafinalonebranchReluLayernormspmmod', 'SAMAdaptermultimodalselectorgamma_nogammafinalonebranchReluBatchnormspmmod',
           'SAMAdaptermultimodalselectorgamma_nogammafinalonebranchRelunormsum', 'SAMAdaptermultimodalselectorgamma_nogammafinalonebranchRelunormsum_concat', 'SAMAdaptermultimodalselectorgamma_nogammafinaltwobranchRelunormsum',
           'BEiTBaseline', 'UniPerceiverAdapter', 'SAMAdapterRGBDEPTH','SAMAdapterRGBDEPTH_levelembed','SAMAdaptermultimodalselectorgamma_nogammafinaltwobranchRelunormsum_concatinj','SAMAdaptermultimodalselectorgamma_nogammafinalonebranchRelunormsumgammalearnable', 'SAMAdaptermultimodalselectorgamma_nogammafinalonebranchReluBatchnormspmmod_nosum',
           'SAMAdaptermultimodal1modselectoronebranchRelunorm','SAMAdaptermultimodal4modselectoronebranchRelunorm', 'SAMAdaptermultimodalnomodselectoronebranch', 'SAMAdaptermultimodal4modselectoronebranchRelunormFPN', 'SAMAdaptermultimodal4modselectoronebranchRelunormlevemb', 'SAMAdaptermultimodal4modselectoronebranchRelunormconcat',
           'SAMAdaptermultimodal4modselectoronebranchRelunormBN', 'SAMAdapterRGB1mod','SAMAdaptermultimodal4modselectoronebranchRelunormseparated', 'SAMAdaptermultimodal4modselectoronebranchRelunormFPNreversed',
           'SAMAdaptermultimodal4modselectoronebranchRelunormconcatless', 'SAMAdaptermultimodal4modselectoronebranchRelunormconcatl2', 'SAMAdaptermultimodal4modselectoronebranchRelunormconcatBN',
           'SAMAdaptermultimodal4modselectoronebranchRelunormconcatTrans','SAMAdapterbimodal4modselectoronebranchRelunorm', 'SAMAdapterbimodal4modselectoronebranchRelunormconcat', 'SAMAdapterbimodal4modselectoronebranchRelunormconcatless', 'SAMAdapterbimodal4modselectoronebranch',
           'SAMAdapterbimodal4modselectoronebranchRelunormconcatlessc1', 'SAMAdapterbimodal4modselectoronebranchRelunormconcatv2','SAMAdaptermultimodal4modselectoronebranchRelunormconcatlessv2', 'SAMAdapterbimodal4modselectoronebranchRelunormconcatlessc1eden', 'SAMAdapterbimodal4modselectoronebranchModFromSp', 'SAMAdapterbimodal4modselectoronebranchModFromSpModfromViT',
           'SAMAdapterbimodal4modselectoronebranchModFromViT', 'SAMAdapterbimodal4modselectoronebranchModFromSpSOFTMAX', 'SAMAdapterbimodal4modselectoronebranchModFromSpModfromViTv2','SAMAdapterbimodal4modselectoronebranchModFromSpModfromViTv3','SAMAdapterbimodal4modselectoronebranchModFromSpModfromViTv4',
           'SAMAdaptermultimodal4modselectoronebranchModFromSp', 'SAMAdaptermultimodal4modselectoronebranchModFromViT', 'SAMAdaptermultimodal4modselectoronebranchModsinglechannelByMod', 'SAMAdapterbimodal4modselectoronebranchModFromSpsmooth', 
           'SAMAdapterbimodal4modselectoronebranchModFromSpSOFTMAX_init', 'SAMAdaptermultimodal4modselectoronebranchModFromSpSOFTMAX','SAMAdapterbimodal4modselectoronebranchModFromSpSOFTMAXDROPATH','SAMAdaptermultimodal4modselectoronebranchModFromSpSOFTMAXDROPATH', 'SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModlighterSAMmod',
           'SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModlighter','SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModlighterSAMmodGELU','SAMAdaptermultimodal4modselectoronebranchModFromSpGELU','SAMAdaptermultimodal4modselectoronebranchModFromSpbigger','SAMAdaptermultimodal4modselectoronebranchModFromSpDROPATH','SAMAdaptermultimodal4modselectoronebranchModFromSplighter', 'SAMAdaptermultimodal4modselectoronebranchModFromSpDROPATHBOTH',
           'SAMAdaptermultimodal4modselectoronebranchModFromSpDROPOUT', 'SAMAdaptermultimodal4modselectoronebranchModFromSpbiggerSOFTMAX','SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModDropathnoRGBbranch', 'SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModDropathnoRGBbranchnoModRGB', 'SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModDropathnoRGBbranchvar', 'SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModDropathnoRGBbranchlighter',
           'SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModDropathnoRGBbranchvarconcat', 'SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModDropathnoRGBbranchvarconcatlightersmart','SAMAdaptermultimodal4modselectoronebranchModsinglechannelByModDropathnoRGBbranchvarconcatsmart','SAMnoAdapter', 'SAMAdapterbimodal2branch',
           'SAMAdapterbimodal2branchconcat', 'SAMAdapterbimodalconcat', 'SAMAdapterbimodalconcatLORA','SAMnoAdapterLORA', 'SAMAdapterbimodal2branchconcatLORA', 'SAMAdapterbimodal2branchconcatGELU','SAMAdapterbimodalconcatGELU','SAMAdapterbimodalconcatSMART','SAMAdapterbimodalconcatSCORESMART','SAMAdapterbimodalconcatSCOREcommon',
           'SAMAdapterbimodalSCOREcommon','SAMAdapterbimodalSCOREcommonLORA','SAMAdapterbimodal4modselectoronebranchEARLYFUSION','SAMAdapterbimodal2branchseq','SAMAdapterbimodal2branchseqfusion','SAMAdapterbimodal2branchseqnofinadd', 'SAMAdapterbimodal2branchseqADA', 'SAMAdapterRGB1moddebug','SAMAdapterbimodalconcatnoRELU','SAMAdapterbimodalconcatnoRELUpatchembedmod','SAMAdapterbimodalconcatnoRELUsumonlyRGB',
           'SAMAdapterbimodalMixMod','SAMAdapterbimodalMixModNewIn','SAMAdapterbimodalMixModNewInTwinConv','SAMAdapterbimodalMixModNewInTwinConvNEW','SAMAdapterbimodalMixModNewInSharedConvNEW','SAMAdapterbimodalMixModNewInTwinConvNEWwithcp', 'SAMAdapterbimodalMixModNewInTwinConvNEWwithcpLORA','SAMAdapterbimodalMixModNewInTwinConvNEWwithcpthinner','SAMAdapterbimodalMixModNewInTwinConvNEWthinner','SAMAdapterbimodalMixModNewInTwinConvNEWTHIN','SAMAdapterbimodalMixModNewInTwinConvNEWwithcpTHIN'
           ,'SAMAdaptermultimodalsingleConvNext', 'SAMAdaptermonomodalNewInConvNEW','SAMAdapterbimodalSumModNewInTwinConvNEW','SAMAdapterbimodalMixModNewInTwinConvNEWSWIN','SAMAdapterbimodalMixModNewInTwinConvNEWwithcpSWIN','SAMAdapterbimodalMixModNewInTwinConvNEWLORA','SAMAdapterbimodalMixModNewInTwinConvNEWwithcpnoweight','SAMAdapterbimodalMixModNewInTwinSPMNEW','SAMAdapterbimodalMixModNewInTwinSPMNEWMS','SAMAdapterbimodalMixModNewInTwinConvNEWconcat','SAMAdapterbimodalMixModNewInTwinCONVNEWMS', 'SAMAdapterbimodalMixModNewInTwinConvNEWFUSION','SAMAdapterbimodalMixModNewInTwinConvNEWFUSIONBETTER','SAMAdapterbimodalMixModNewInTwinConvNEWFUSIONSIMPLER','SAMAdapterbimodalMixModNewInTwinConvNEWFUSIONMEDIUM'] #'SAMAdapterbimodal2branchMINK','SAMAdapterRGB1modMinkovsky','SAMAdapterbimodal2branchconcatMINK','SAMAdapterbimodalconcatMINK',
