# Copyright (c) Shanghai AI Lab. All rights reserved.
from .beit_adapter import BEiTAdapter
from .beit_baseline import BEiTBaseline
from .vit_adapter import ViTAdapter
from .vit_baseline import ViTBaseline
from .uniperceiver_adapter import UniPerceiverAdapter
from .beit_adapter_multimodal import BEiTAdaptermultimodal
from .image_encoder import ImageEncoderViT
from .image_encoder_adapter_multimodal import SAMAdaptermultimodal
from .image_encoder_adapter_onlyDEPTH import SAMAdapterRGBDEPTH
from .image_encoder_adapter_onlyDEPTH_levelembed import SAMAdapterRGBDEPTH_levelembed
from .image_encoder_adapter_multimodal_1mod_selector_image_based_one_adapter_branch_relu_norm import SAMAdaptermultimodal1modselectoronebranchRelunorm
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm import SAMAdaptermultimodal4modselectoronebranchRelunorm
from .image_encoder_adapter_multimodal_nomod_selector_image_based_one_adapter_branch import SAMAdaptermultimodalnomodselectoronebranch
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_FPN import SAMAdaptermultimodal4modselectoronebranchRelunormFPN
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_level_embed import SAMAdaptermultimodal4modselectoronebranchRelunormlevemb
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concat import SAMAdaptermultimodal4modselectoronebranchRelunormconcat
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_BN import SAMAdaptermultimodal4modselectoronebranchRelunormBN
from .image_encoder_adapter_only1mod import SAMAdapterRGB1mod
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_modality_selector_separated import SAMAdaptermultimodal4modselectoronebranchRelunormseparated
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_FPN_reversed import SAMAdaptermultimodal4modselectoronebranchRelunormFPNreversed
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concat_less import SAMAdaptermultimodal4modselectoronebranchRelunormconcatless
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concat_l2 import SAMAdaptermultimodal4modselectoronebranchRelunormconcatl2
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concatBN import SAMAdaptermultimodal4modselectoronebranchRelunormconcatBN
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concat_transpose_conv import SAMAdaptermultimodal4modselectoronebranchRelunormconcatTrans
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_relu_norm import SAMAdapterbimodal4modselectoronebranchRelunorm
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concat import SAMAdapterbimodal4modselectoronebranchRelunormconcat
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concat_less import SAMAdapterbimodal4modselectoronebranchRelunormconcatless
from .image_encoder_adapter_bimodal_4mod_one_adapter_branch import SAMAdapterbimodal4modselectoronebranch
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concat_less_c1 import SAMAdapterbimodal4modselectoronebranchRelunormconcatlessc1
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concatv2 import SAMAdapterbimodal4modselectoronebranchRelunormconcatv2
from .image_encoder_adapter_multimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concat_lessv2 import SAMAdaptermultimodal4modselectoronebranchRelunormconcatlessv2
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_relu_norm_concat_less_c1_eden import SAMAdapterbimodal4modselectoronebranchRelunormconcatlessc1eden
from .image_encoder_adapter_bimodal_4mod_selector_image_based_one_adapter_branch_modality_selector_from_spatial_feature import SAMAdapterbimodal4modselectoronebranchModFromSp

__all__ = ['ViTBaseline', 'ViTAdapter','BEiTAdapter', 'ImageEncoderViT','BEiTBaseline',
           'UniPerceiverAdapter', 'SAMAdaptermultimodal','SAMAdapterRGBDEPTH','SAMAdapterRGBDEPTH_levelembed',
           'SAMAdaptermultimodal1modselectoronebranchRelunorm','SAMAdaptermultimodal4modselectoronebranchRelunorm', 'SAMAdaptermultimodalnomodselectoronebranch', 'SAMAdaptermultimodal4modselectoronebranchRelunormFPN', 'SAMAdaptermultimodal4modselectoronebranchRelunormlevemb', 'SAMAdaptermultimodal4modselectoronebranchRelunormconcat',
           'BEiTAdaptermultimodal', 'SAMAdapterRGB1mod','SAMAdaptermultimodal4modselectoronebranchRelunormseparated', 'SAMAdaptermultimodal4modselectoronebranchRelunormFPNreversed',
            'SAMAdaptermultimodal4modselectoronebranchRelunormconcatless', 'SAMAdaptermultimodal4modselectoronebranchRelunormconcatl2', 'SAMAdaptermultimodal4modselectoronebranchRelunormconcatBN',
            'SAMAdaptermultimodal4modselectoronebranchRelunormBN', 'SAMAdaptermultimodal4modselectoronebranchRelunormconcatTrans','SAMAdapterbimodal4modselectoronebranchRelunorm', 'SAMAdapterbimodal4modselectoronebranchRelunormconcat', 'SAMAdapterbimodal4modselectoronebranchRelunormconcatless', 'SAMAdapterbimodal4modselectoronebranch',
            'SAMAdapterbimodal4modselectoronebranchRelunormconcatlessc1', 'SAMAdapterbimodal4modselectoronebranchRelunormconcatv2','SAMAdaptermultimodal4modselectoronebranchRelunormconcatlessv2', 'SAMAdapterbimodal4modselectoronebranchRelunormconcatlessc1eden', 'SAMAdapterbimodal4modselectoronebranchModFromSp'
           ]

# __all__ = ['ViTBaseline', 'ViTAdapter',
#            'BEiTAdapter', 'ImageEncoderViT',
#            'BEiTAdaptermultimodal','SAMAdaptermultimodal','SAMAdaptermultimodalnogamma','SAMAdaptermultimodalselectorgamma', 'SAMAdaptermultimodalselectorgamma_nogammac1', 'SAMAdaptermultimodalselectorgamma_nogammafinal','SAMAdaptermultimodalselectorgamma_nogammafinalonebranch', 'SAMAdaptermultimodalselectorgamma_nogammafinalonebranchLayerNorm','SAMAdaptermultimodalselectorgamma_nogammafinalonebranchReluNorm', 'SAMAdaptermultimodalselectorgamma_nogammafinalonebranchSoftmax','SAMAdaptermultimodalselectorgamma_nogammafinalonebranchReluLayernorm', 'SAMAdaptermultimodalselectorgamma_nogammafinalonebranchReluLayernormspmmod', 'SAMAdaptermultimodalselectorgamma_nogammafinalonebranchReluBatchnormspmmod',
#            'SAMAdaptermultimodalselectorgamma_nogammafinalonebranchRelunormsum', 'SAMAdaptermultimodalselectorgamma_nogammafinalonebranchRelunormsum_concat', 'SAMAdaptermultimodalselectorgamma_nogammafinaltwobranchRelunormsum',
#            'BEiTBaseline', 'UniPerceiverAdapter', 'SAMAdapterRGBDEPTH','SAMAdapterRGBDEPTH_levelembed','SAMAdaptermultimodalselectorgamma_nogammafinaltwobranchRelunormsum_concatinj','SAMAdaptermultimodalselectorgamma_nogammafinalonebranchRelunormsumgammalearnable', 'SAMAdaptermultimodalselectorgamma_nogammafinalonebranchReluBatchnormspmmod_nosum',
#            'SAMAdaptermultimodal1modselectoronebranchRelunorm','SAMAdaptermultimodal4modselectoronebranchRelunorm', 'SAMAdaptermultimodalnomodselectoronebranch', 'SAMAdaptermultimodal4modselectoronebranchRelunormFPN', 'SAMAdaptermultimodal4modselectoronebranchRelunormlevemb', 'SAMAdaptermultimodal4modselectoronebranchRelunormconcat',
#            'SAMAdaptermultimodal4modselectoronebranchRelunormBN', 'SAMAdapterRGB1mod','SAMAdaptermultimodal4modselectoronebranchRelunormseparated', 'SAMAdaptermultimodal4modselectoronebranchRelunormFPNreversed',
#            'SAMAdaptermultimodal4modselectoronebranchRelunormconcatless', 'SAMAdaptermultimodal4modselectoronebranchRelunormconcatl2', 'SAMAdaptermultimodal4modselectoronebranchRelunormconcatBN',
#            'SAMAdaptermultimodal4modselectoronebranchRelunormconcatTrans','SAMAdapterbimodal4modselectoronebranchRelunorm', 'SAMAdapterbimodal4modselectoronebranchRelunormconcat', 'SAMAdapterbimodal4modselectoronebranchRelunormconcatless', 'SAMAdapterbimodal4modselectoronebranch',
#            'SAMAdapterbimodal4modselectoronebranchRelunormconcatlessc1', 'SAMAdapterbimodal4modselectoronebranchRelunormconcatv2','SAMAdaptermultimodal4modselectoronebranchRelunormconcatlessv2', 'SAMAdapterbimodal4modselectoronebranchRelunormconcatlessc1eden', 'SAMAdapterbimodal4modselectoronebranchModFromSp']
